security:
  basic:
    enabled: false
  user:
      password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/uam
  ldap:
    embedded:
      ldif: classpath:schema.ldif


# Define the port where the UAA server would be running
server:
  port: 9091
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: false

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: WARN
    com.softcell.gonogo.*: DEBUG


gng:
  security:
    jwt:
      pass: mySecretKey
