
info:
  project:
    version: 1.0.0 

security:
  basic:
    enabled: false
  user:
      password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

spring:
  message:
    basen
  data:
    mongodb:
      uri: ${UAA_MONGO_URL:mongodb://localhost:27017/uam}
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:7073}
    enabled: true
    locator:
      discovery:
        enabled: true
  
  ldap:
    embedded:
      ldif: classpath:schema.ldif


# Define the port where the UAA server would be running
server:
  port: 7072
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: false


ribbon:
  eureka:
    enabled: true

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

  

logging:
  level:
    com.softcell.gonogo.*: DEBUG




