
info:
  project:
    version: 1.0.0 

ribbon:
  eureka:
    enabled: true

# See http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html
zuul: # those values must be configured depending on the application specific needs
  debug: 
    request: true
  routes:
    resource-server:
      path: /resource/**
      service-id: resource-server
      strip-prefix: true
    auth-server:
      sensitiveHeaders:
      path: /uaa/**
      service-id: auth-server
      stripPrefix: false
    social-client:
      path: /social/**
      service-id: social-client
      strip-prefix: true
    card-statement: 
      path: /card-statement/** 
      service-id: card-statement
      strip-prefix: true
    statement-service:
      path: /statement-service/**
      service-id: statement-service
      strip-prefix: true
    creditcard-service:
      path: /creditcard-service/**
      service-id: creditcard-service
      strip-prefix: true
  add-proxy-headers: true

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://auth-server/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: uiapplication
      clientSecret: secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn2ZWHYw724KeMucwgoga
          SiqOunCFSUaqYdZUmHxEqxQmey+ezJ20PHzl+YIJrns/cNPM1Nqsy6ZT5MUbGgkf
          t+1bOSLZo4ywfk3nWeMfWt2MDfTgxmIZTHeF/WWViz00uzcHfXSoW5U4Afs2fqFB
          gDoiS/w6lxTi/nE+FeSLT8VajSqRoudXHi5HitnrNt+Rqf78MuezWJvhiqO/88Ac
          lAJ0Qheon15zvmjJgNBg2Mpy+ab4GgcU1mezZYUl8fwfup8Y6fhCZkvFDFMl2h8O
          5d8TDl4ssjwjMQqQgcVKhy5HvA9AUcOP0wc+G46VN4F9771cBWc/60oCzUqRVa1b
          RQIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource


spring:
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:7073}
    enabled: true
    locator:
      discovery:
        enabled: true

logging:
  level.org.springframework.security: DEBUG
