info:
  project:
    version: 1.0.0

server:
  port: 7075

test:
  key: prateek-event-bus-test

eureka:
  instance:
    appname: resource-server
    instanceId: resource-server:${spring.application.instance-id:${random.value}}
    hostname: localhost
    port: 7071
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: ${info.project.version}
  client:
    enabled: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


ribbon:
  eureka:
    enabled: true


# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:7073}
    enabled: true
    locator:
      discovery:
        enabled: true

logging:
  level.org.springframework.security: DEBUG